#:schema node_modules/wrangler/config-schema.json
name = "suublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b8d650c018fe4c1b92379d6880e3a8b8" }
]

[assets]
directory = "./public"
